// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tobuanrwkcfwndooseyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvYnVhbnJ3a2Nmd25kb29zZXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzE1ODcsImV4cCI6MjA2NTUwNzU4N30._hFJA1iWecgwGHQdYfGFr3nSXph0-VCxvavcpSoDjfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);